34 assembler wildcard to quast
CUMoellerLab/sn-mg-pipeline pull request #41
Opened 2021-09-03 04:22 UTC by DanielSprockett

Addresses PR #34

2021-09-03 14:33 UTC, tanaes requested changes
A few conflicts found in the assembler wildcards. Now that PR#40 is merged, would also be useful to pull main.

2021-09-03 14:33 UTC, tanaes commented on resources/snakefiles/assemble.smk
>      log:
Log file also needs `{assembler}`

2021-09-03 14:33 UTC, tanaes commented on resources/snakefiles/assemble.smk
> +        "output/assemble/{assembler}/multiqc/multiqc.html"
There's a conflict here -- the `expand` function in `input` is running multiqc on *all* the assemblers, but the output is per-assembler. We need to pick one or the other.

I'd maybe suggest doing multiqc for the whole shebang, as the point is comparison. So output should be in `output/assemble/multiqc`, and log can remain the same.

2021-09-03 14:33 UTC, tanaes commented on resources/snakefiles/assemble.smk
>                                   assembler=config['assemblers'],
for metaquast we to only run on a single assembly, so we don't want to expand `assembler` from `config['assemblers']`; instead, we should pass `assembler=wildcards.assembler` and have `assembler` populated via and `expand` statement in `multiqc_metaquast`

2021-09-05 23:49 UTC, DanielSprockett commented
I think I may have made a mistake when merging the previous pull request, but I think I've made all of the requested changes.

2021-09-05 23:51 UTC, DanielSprockett commented
wait, no, I think I accidentally pushed these changes to PR #35.

2021-09-06 04:58 UTC, DanielSprockett commented
See also:
https://github.com/DanielSprockett/sn-mg-pipeline/commit/7bdaf17aec9ae7deca640771e01f20b14593e0bc

I believe I fixed everything in that branch, as well.

2021-09-06 20:39 UTC, merged